# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BYU Web Style Guide
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/byu-style-guide" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  specs_style:
    output: true
    name: Style
    order: 1
    description: >-
      General styling guidelines
    examples:
      - color palettes
      - typography
      - iconography
  specs_theme:
    output: true
    name: Theme
    order: 2
    description: >-
      Elements that belong on every BYU page
    examples:
      - header
      - footer
      - navigation
  specs_layout:
    output: true
    name: Layout
    order: 3
    description: >-
      Recommendations and patterns for overall page structure
  specs_organization:
    output: true
    name: Organization
    order: 4
    description: >-
      How to assemble pages into one cohesive site
  specs_components:
    output: true
    name: Components
    order: 5
    description: >-
      Small, reusable design elements for building pages
    examples:
      - heroes
      - cards
      - buttons
  specs_patterns:
    output: true
    name: Patterns
    order: 6
    description: >-
      Larger design elements
    examples:
      - dialog boxes
      - faculty directory
      - news stories

# Build settings
markdown: kramdown

livereload: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - specs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
